### ISSUE TITLE
As a developer I want to update the contact section

### ISSUE THREAD

**Issue by asghaier** [espritlibreclub/git101#1]
The use cannot know the correct contact information and cannot see a correct copy right information in the footer.

### Acceptance Criteria
1. As a site visitor I want to be able to see the contact information
2. As a site visitor I want to be able to see a map
3. As a site visitor I want to be able to see updated copyright information

### Tasks
- [ ] As a developer I want to update the contact information in the html
- [ ] As a developer I want update the google map region
- [ ] As a developer I want to update the footer region
